name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        ruby: [3.0, 3.1]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: setup gems
      run: bundle install --jobs 4 --retry 3
    - name: run test
      run: bundle exec rake spec
